version: "3.9"

networks:
  MYCOURSEVILLE:
    driver: bridge

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - "443:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - MYCOURSEVILLE
  php:
    build: .
    image: my_course_ville-php
    container_name: myCourseVille_php
    volumes:
      - ..:/app:cached
      - ../storage/app/public:/app/public/storage:cached
    working_dir: /app
    ports:
      - "9090:9000"
    networks:
      - MYCOURSEVILLE
  nginx:
    image: nginx:stable-alpine
    container_name: myCourseVille_nginx
    ports:
      - "8100:80"
    expose:
      - "80"
    volumes:
      - ./nginx.web.conf:/etc/nginx/conf.d/default.conf
      - ..:/app
      - ../storage/app/public:/app/public/storage:cached
    working_dir: /app
    depends_on:
      - php
    environment:
      - VIRTUAL_HOST=myCourseVille.localhost
      - VIRTUAL_PORT=80
    networks:
      - MYCOURSEVILLE
  mysql:
    image: mariadb:10.4
    container_name: myCourseVille_mysql
    volumes:
      - ../.database:/var/lib/mysql:delegated
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - MYCOURSEVILLE
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myCourseVille_phpMyAdmin
    ports:
      - "8200:80"
    expose:
      - "80"
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 200M
      VIRTUAL_HOST: "phpmyadmin.myCourseVille.localhost"
      VIRTUAL_PORT: 80
    networks:
      - MYCOURSEVILLE
  redis:
    image: redis:6.2.6-alpine3.14
    container_name: myCourseVille_redis
    command: redis-server --appendonly yes
    volumes:
      - ../.redis:/data
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    networks:
      - MYCOURSEVILLE